[package]
name = "witnet_pool"
version = "0.1.0"
authors = ["Adán Sánchez de Pedro Crespo <adan@witnet.io>"]
workspace = ".."

[dependencies]
serde = "~1.0.27"
serde_derive = "~1.0.27"
time = "~0.1.39"

witnet_core = { path = "../core" }
