# You can read more about all the configuration params in
# https://docs.witnet.io/configuration/toml-file/
[connections]
# Server address tells what local interface and port the Witnet node server should bind to.
# This will probably look like `0.0.0.0:21337` or `192.168.x.x:21337`, but it totally depends on your local network.
server_addr = "0.0.0.0:21337"
# Public address needs to match your *public* IP and port, assuming your router is configured to forward incoming
# connections to the local IP of the device the node is running. Failure to configure this setting will result in your
# node not receiving inbound connections (see: https://docs.witnet.io/try/run-a-node/#open-your-ports).
public_addr = "0.0.0.0:21337"
# List of bootstrap peer addresses. The first time that a node runs, it connects to some of these addresses and query
# them for a list of all the addresses they know. From that moment on, the addresses listed here are not given any
# preference over addresses that have been discovered in any way.
known_peers = [
    "82.213.202.243:21337",
    "188.127.180.67:21337",
    "188.127.180.67:21338",
    "188.127.180.67:21339",
    "188.127.180.67:21340",
    "188.127.180.67:21341",
    "188.127.180.67:21342",
    "188.127.180.67:21343",
    "188.127.180.67:21344",
    "188.127.180.67:21345",
    "188.127.180.67:21346",
    "188.127.180.67:21347",
    "188.127.180.67:21348",
    "188.127.180.67:21349",
    "52.166.178.145:21337",
    "52.166.178.145:22337",
    "52.166.178.145:23337",
    "52.166.178.145:24337",
    "52.166.178.145:25337",
    "52.166.178.145:26337",
    "159.69.146.71:21337",
    "159.69.146.71:21338",
    "159.69.146.71:21339",
    "159.69.146.71:21340",
    "159.69.146.71:21341",
    "159.69.146.71:21342",
    "159.69.146.71:21343",
    "159.69.146.71:21344",
    "159.69.146.71:21345",
    "159.69.146.71:21346",
    "159.69.146.71:21347",
    "159.69.146.71:21349",
    "159.69.146.71:21350",
    "159.69.146.71:21351",
    "159.69.146.71:21352",
    "62.171.170.204:21337"
]
# How many peer connections to stablish before considering that is safe to decide what the best chain tip is, based on
# the beacons that those peers are announcing.
outbound_limit = 16
# Period for opening new peer connections while the current number of peers is lower than `outbound_limit`.
bootstrap_peers_period_seconds = 1

[storage]
# Path of the folder where RocksDB storage files will be written to.
db_path = ".witnet/storage"

[jsonrpc]
# Enables or disables the JSON-RPC server. This is needed for using the CLI methods of the node.
enabled = true
# The address (IP and port) which the JSON-RPC server binds to.
# WARNING: this should be kept to a local, private address (e.g. 127.0.0.1) to prevent any device in your local network
# (and potentially, the internet) from messing with your JSON-RPC server.
server_address = "127.0.0.1:21338"

[ntp]
# Period for checking the local system clock drift against a public NTP server.
update_period_seconds = 8000000

[mining]
# Enable or disable mining and participation in resolving data requests.
enabled = true
# Limit the number of retrievals that the node will perform during a single epoch. Due to the locking, highly
# side-effected nature of performing HTTP GET requests, a limit needs to be enforced on the number of retrievals that
# we are willing to perform by unit of time.
# Raising this limit too high may make the node unresponsive to time-critical events, which could potentially lead to
# desynchronization, forking or slashing.
# This is assumed to be a safe default and it should never cause any node to refrain from participating in data requests
# for which it was eligible.
data_request_max_retrievals_per_epoch = 30
# Limit the number of milliseconds that the node is willing to wait for a data source in from data request to response.
data_request_timeout_milliseconds = 2000
# Path for the `genesis_block.json` file that contains the initial wit allocations that need to be built into the first
# block in the block chain.
genesis_path = ".witnet/config/genesis_block.json"
# `mint_external_address` and `mint_external_percentage` enable splitting the mint reward between the node's
# own address and an "external" address, e.g. a the address of a wallet. `mint_external_percentage` indicates
# the percentage of the block rewards that will be assigned to `mint_external_address` (50% by default)
#mint_external_address = "twit1jqgf4rxjrgas3kdhj3t4cr3mg3n33m8zw0aglr"
#mint_external_percentage = 50

[log]
# Logging level, i.e. from more verbose to quieter: "trace" > "debug" > "info" > "warn" > "error" > "none"
level = "debug"
# Automated bug reporting (helps the community improve the software)
sentry_telemetry = true

[wallet]
# Tell the wallet component whether it is running on a testnet environment.
testnet = true
# The address (IP and port) of a Witnet node's JSON-RPC server. This should normally match `json_rpc.server_address`.
node_url = "127.0.0.1:21338"
