[package]
name = "witnet_chain"
version = "0.1.0"
authors = ["Adán Sánchez de Pedro Crespo <adan@witnet.io>"]
workspace = ".."

[dependencies]
bitflags = "1.0.1"
serde = "~1.0.27"
serde_derive = "~1.0.27"

witnet_core = { path = "../core" }
witnet_store = { path = "../store" }
